export const Colors = {
  white: '#FFFFFF',
  black: '#000000',
  appLoaderBackgroundColor: 'rgba(0,0,0, .6)',
  buttonPrimaryColor: '#E2502A',
  tabBarInactiveColor: '#ACB1B5',
  subHeadingTextColor: '#373A3C',
  textInputLabelTextColor: '#171717',
  textInputBorderColor: '#EEEEEE',
  errorTextColor: '#E2502A',
  plusIconButtonColor: '#CD3B1C',
  departmentTextColor: '#ACB1B5',
  timeAgoTextColor: '#818A91',
  iconContainerColor: '#FCEEEA',
  searchInputBackgroundColor: '#C74625',
  searchInputTextColor: '#FFB39F',
  iconBackground: '#F1F1F1',
  danger: '#E50000',
  incomingCallTextBackground: '#F8F7F7',
  subHeadingColor: '#616161',
  emailSentHeadingColor: '#212121',
  splashScreenColor: '#E2502A',
  searchInputPlaceHolderColor: '#9E9E9E',
  recordingPlayerBorder: '#F5F5F5',
  recordingPlayerWaveformColor: '#D4D4D4',
  recordingPlayerBackgroundColor: '#F8FAFB',
  sentMessageCardColor: '#FCEEEA',
  receiveMessageCardColor: '#EEEEEE',
  sendMessagePlaceholderColor: '#9E9E9E',
  sendMessageShadowColor: 'rgba(0, 0, 0, 0.05)',
  clearTextColor: '#D25A38',
  selectedCampaignTextColor: '#2A61E2',
  selectedCampaignPillContainer: '#EAEFFC',
  imagePreviewScreenColor: '#F8FAFB',
  tagBackgroundColor: '#9F9F9F',
  drawerCardColor: '#FEF8F7',
  linkedContactRolColor: '#0F4BD9',
  notesBGColor: '#FFF8D5',
  notesBGBorderColor: '#FAEBAB',
};
