export const ScreensName = {
  SplashScreen: 'SplashScreen',
  AuthStackScreen: 'AuthStackScreen',
  AppStackScreen: 'AppStackScreen',
  BottomTabScreen: 'BottomTabScreen',
  SignInScreen: 'SignInScreen',
  CallsScreen: 'CallsScreen',
  ContactsScreen: 'ContactsScreen',
  DialScreen: 'DialScreen',
  MessagesScreen: 'MessagesScreen',
  VoicemailsScreen: 'VoicemailsScreen',
  DrawerNavigatorScreen: 'DrawerNavigatorScreen',
  CallDetailScreen: 'CallDetailScreen',
  ContactDetailScreen: 'ContactDetailScreen',
  ContactPropertiesDetailScreen: 'ContactPropertiesDetailScreen',
  ContactInfoUpdateScreen: 'ContactInfoUpdateScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  EmailSentScreen: 'EmailSentScreen',
  ChatHistoryScreen: 'ChatHistoryScreen',
  ImagesPreviewScreen: 'ImagesPreviewScreen',
  LiveCallScreen: 'LiveCallScreen',
  CallDispositionScreen: 'CallDispositionScreen',
};

export const Strings = {
  MemberLogin: 'Member Login',
  TheAllInOneMarketingAndBusinessSoftwareSolution:
    'The All In One Marketing and Business Software Solution',
  EnterEmail: 'Enter Email',
  EnterUsername: 'Enter Username',
  Password: 'Password',
  EnterPassword: 'Enter Password',
  SignIn: 'Sign in',
  ForgetPassword: 'Forgot Password?',
  ByLoggingInYouAreAgreeingToOur: 'By logging in, you are agreeing to our ',
  TermsConditions: 'Terms & Conditions',
  AllMessages: 'All Messages',
  CallHistory: 'Call History',
  SearchByNamePhone: 'Search by name, phone...',
  SearchByNamePhoneEmail: 'Search by name, phone or email...',
  ForgotPassword: 'Forgot Password',
  PleaseEnterYourRegisteredEmailAddressSoWeWillSendYouLinkOnYourEmail:
    'Please enter your registered email address, so we will send you link on your email',
  SendResetLink: 'Send Reset Link',
  RememberIt: 'Remember It? ',
  Signin: 'Sign In',
  EmailSent: 'Email Sent!',
  APasswordResetLinkHasBeenSentToYourEmailAddress:
    'A password reset link has been sent to your email address.',
  BackToLogin: 'Back to Login',
  profitDial: 'REI BlackBook',
  SettingUp: 'Setting up...',
  CallNewUser: 'Call New Contact',
  CallExistingUser: 'Call Existing Contact',
  TextNewUser: 'Text New Contact',
  TextExistingUser: 'Text Existing Contact',
  NoCallHistory: 'No Call History',
  MakeACall: 'Make a call',
  NoChatHistory: 'No Chat History',
  NoMessagesInYourInboxYetStartChattingWithPeopleAroundYou:
    'No messages in your inbox, yet! Start chatting with people around you.',
  NoVoicemailHistory: 'No Voicemail History',
  NoCallRecordingHistory: 'No Call Recording History',
  ItLooksLikeYourVoicemailInboxIsCurrentlyEmptyWhenNewVoicemailsArriveTheyWillAppearHere:
    'It looks like your voicemail inbox is currently empty. When new voicemails arrive, they will appear here.',
  ItLooksLikeYourCallRecordingInboxIsCurrentlyEmptyWhenNewCallRecordingsArriveTheyWillAppearHere:
    'It looks like your call recording inbox is currently empty. When new call recordings arrive, they will appear here.',
  ViewContactDetails: 'View Contact Details',
  TriggerWorkflow: 'Trigger Workflow',
  UpdateContact: 'Update Contact',
  Cancel: 'Cancel',
  CreateNewContact: 'Create New Contact',
  AssignToExistingContact: 'Assign to Existing Contact',
  Camera: 'Camera',
  PhotoGallery: 'Photo Gallery',
  TypeMessage: 'Type a message ...',
  WriteYourComment: 'Write your comment @ all',
  WriteANote: 'Write a note',
  AddAComment: 'Add a comment',
  TextAs: 'Text as:',
  Recordings: 'Recordings',
  SelectedCampaign: 'Selected Campaign: ',
  Clear: 'Clear',
  Preview: 'Preview',
  NoContactFound: 'No Contact Found',
  ItlookslikeyouhaventaddedanycontactsStartbyaddingyourfirstcontact:
    'It looks like you haven’t added any contacts. Start by adding your first contact.',
};
